"""Initial Migration

Revision ID: e40da58dbc96
Revises: 
Create Date: 2025-06-05 14:52:07.292141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40da58dbc96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salary')
    op.drop_column('admin', 'salary')
    # ### end Alembic commands ###
